import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Ksenia's Russian School",
    template: "%s | Ksenia's Russian School",
  },
  description:
    "Learn Russian the smart way with Ksenia. Track your mistakes, master them with spaced repetition, and become fluent faster. Учись с Ксенией!",
  keywords: [
    "Russian language",
    "learn Russian",
    "Russian lessons",
    "spaced repetition",
    "language learning",
    "Russian tutor",
    "flashcards",
    "vocabulary",
    "Ksenia",
    "учить русский",
  ],
  authors: [{ name: "Ksenia's Russian School" }],
  creator: "Ksenia's Russian School",
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "https://ksenia-russian.vercel.app"
  ),
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: "ru_RU",
    siteName: "Ksenia's Russian School",
    title: "Ksenia's Russian School",
    description:
      "Learn Russian the smart way. Track your mistakes and master them with spaced repetition.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ksenia's Russian School",
    description:
      "Learn Russian the smart way. Track your mistakes and master them with spaced repetition.",
    creator: "@kseniarussian",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Icons are automatically generated by icon.tsx and apple-icon.tsx
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
